/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedEntregadoresRouteImport } from './routes/_authenticated/entregadores'
import { Route as AuthenticatedEntregadorRouteImport } from './routes/_authenticated/entregador'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PedidoIdStatusRouteImport } from './routes/pedido.$id.status'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos.$id'
import { Route as ApiPublicWebhookWhatsappRouteImport } from './routes/api/public/webhook/whatsapp'
import { Route as ApiPublicIntegracoesMercadopagoCallbackRouteImport } from './routes/api/public/integracoes/mercadopago/callback'

const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregadoresRoute =
  AuthenticatedEntregadoresRouteImport.update({
    id: '/entregadores',
    path: '/entregadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntregadorRoute = AuthenticatedEntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PedidoIdStatusRoute = PedidoIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => PedidoIdRoute,
} as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPedidosRoute,
} as any)
const ApiPublicWebhookWhatsappRoute =
  ApiPublicWebhookWhatsappRouteImport.update({
    id: '/api/public/webhook/whatsapp',
    path: '/api/public/webhook/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegracoesMercadopagoCallbackRoute =
  ApiPublicIntegracoesMercadopagoCallbackRouteImport.update({
    id: '/api/public/integracoes/mercadopago/callback',
    path: '/api/public/integracoes/mercadopago/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/plano': typeof PlanoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entregador': typeof AuthenticatedEntregadorRoute
  '/entregadores': typeof AuthenticatedEntregadoresRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedido/$id': typeof PedidoIdRouteWithChildren
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedido/$id/status': typeof PedidoIdStatusRoute
  '/api/public/webhook/whatsapp': typeof ApiPublicWebhookWhatsappRoute
  '/api/public/integracoes/mercadopago/callback': typeof ApiPublicIntegracoesMercadopagoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/plano': typeof PlanoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entregador': typeof AuthenticatedEntregadorRoute
  '/entregadores': typeof AuthenticatedEntregadoresRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedido/$id': typeof PedidoIdRouteWithChildren
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedido/$id/status': typeof PedidoIdStatusRoute
  '/api/public/webhook/whatsapp': typeof ApiPublicWebhookWhatsappRoute
  '/api/public/integracoes/mercadopago/callback': typeof ApiPublicIntegracoesMercadopagoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/plano': typeof PlanoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entregador': typeof AuthenticatedEntregadorRoute
  '/_authenticated/entregadores': typeof AuthenticatedEntregadoresRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedido/$id': typeof PedidoIdRouteWithChildren
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedido/$id/status': typeof PedidoIdStatusRoute
  '/api/public/webhook/whatsapp': typeof ApiPublicWebhookWhatsappRoute
  '/api/public/integracoes/mercadopago/callback': typeof ApiPublicIntegracoesMercadopagoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/plano'
    | '/admin'
    | '/ajuda'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/entregador'
    | '/entregadores'
    | '/estoque'
    | '/pedidos'
    | '/perfil'
    | '/loja/$slug'
    | '/pedido/$id'
    | '/pedidos/$id'
    | '/pedido/$id/status'
    | '/api/public/webhook/whatsapp'
    | '/api/public/integracoes/mercadopago/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/plano'
    | '/admin'
    | '/ajuda'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/entregador'
    | '/entregadores'
    | '/estoque'
    | '/pedidos'
    | '/perfil'
    | '/loja/$slug'
    | '/pedido/$id'
    | '/pedidos/$id'
    | '/pedido/$id/status'
    | '/api/public/webhook/whatsapp'
    | '/api/public/integracoes/mercadopago/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/plano'
    | '/_authenticated/admin'
    | '/_authenticated/ajuda'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/entregador'
    | '/_authenticated/entregadores'
    | '/_authenticated/estoque'
    | '/_authenticated/pedidos'
    | '/_authenticated/perfil'
    | '/loja/$slug'
    | '/pedido/$id'
    | '/_authenticated/pedidos/$id'
    | '/pedido/$id/status'
    | '/api/public/webhook/whatsapp'
    | '/api/public/integracoes/mercadopago/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlanoRoute: typeof PlanoRoute
  LojaSlugRoute: typeof LojaSlugRoute
  PedidoIdRoute: typeof PedidoIdRouteWithChildren
  ApiPublicWebhookWhatsappRoute: typeof ApiPublicWebhookWhatsappRoute
  ApiPublicIntegracoesMercadopagoCallbackRoute: typeof ApiPublicIntegracoesMercadopagoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregadores': {
      id: '/_authenticated/entregadores'
      path: '/entregadores'
      fullPath: '/entregadores'
      preLoaderRoute: typeof AuthenticatedEntregadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregador': {
      id: '/_authenticated/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof AuthenticatedEntregadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pedido/$id/status': {
      id: '/pedido/$id/status'
      path: '/status'
      fullPath: '/pedido/$id/status'
      preLoaderRoute: typeof PedidoIdStatusRouteImport
      parentRoute: typeof PedidoIdRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedPedidosRoute
    }
    '/api/public/webhook/whatsapp': {
      id: '/api/public/webhook/whatsapp'
      path: '/api/public/webhook/whatsapp'
      fullPath: '/api/public/webhook/whatsapp'
      preLoaderRoute: typeof ApiPublicWebhookWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integracoes/mercadopago/callback': {
      id: '/api/public/integracoes/mercadopago/callback'
      path: '/api/public/integracoes/mercadopago/callback'
      fullPath: '/api/public/integracoes/mercadopago/callback'
      preLoaderRoute: typeof ApiPublicIntegracoesMercadopagoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPedidosRouteChildren {
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
}

const AuthenticatedPedidosRouteChildren: AuthenticatedPedidosRouteChildren = {
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
}

const AuthenticatedPedidosRouteWithChildren =
  AuthenticatedPedidosRoute._addFileChildren(AuthenticatedPedidosRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntregadorRoute: typeof AuthenticatedEntregadorRoute
  AuthenticatedEntregadoresRoute: typeof AuthenticatedEntregadoresRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntregadorRoute: AuthenticatedEntregadorRoute,
  AuthenticatedEntregadoresRoute: AuthenticatedEntregadoresRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PedidoIdRouteChildren {
  PedidoIdStatusRoute: typeof PedidoIdStatusRoute
}

const PedidoIdRouteChildren: PedidoIdRouteChildren = {
  PedidoIdStatusRoute: PedidoIdStatusRoute,
}

const PedidoIdRouteWithChildren = PedidoIdRoute._addFileChildren(
  PedidoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PlanoRoute: PlanoRoute,
  LojaSlugRoute: LojaSlugRoute,
  PedidoIdRoute: PedidoIdRouteWithChildren,
  ApiPublicWebhookWhatsappRoute: ApiPublicWebhookWhatsappRoute,
  ApiPublicIntegracoesMercadopagoCallbackRoute:
    ApiPublicIntegracoesMercadopagoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
